logging:
  root_log_level: INFO
  # When running in k8s, use JSON logger via env setting
  # formatter: json
  formatter: "standard"
  child_log_levels:
    mchpy: DEBUG
    flex_container_orechestrator.config.http_audit: INFO
main:
  app_name: flex-container-orchestrator
  time_settings:
    # Number of hours between timesteps
    tincr: 1
    # Number of timesteps to run Flexpart with (temporarily set to 6 timesteps but operational config is 90)
    tdelta: 6
    # Frequency of Flexpart runs in hours
    tfreq_f: 6
    # Frequency of IFS runs in hours
    tfreq: 6
