listeners:
  - event: dissemination
    request:
      destination: S7Y
      class: od
      expver: 0001
      domain: g
      stream: [oper, scda]
    triggers:
      - type: log
        path: avisoLogs/log_aviso_notifications.log
      - type: command
        working_dir: $HOME/flex-container-orchestrator/
        command: >
          poetry run python3 flex_container_orchestrator/main.py \
            --step "${request.step}" \
            --date "${request.date}" \
            --time "${request.time}" \
            --location "${location}" >> ../avisoLogs/log_run_${request.date}_${request.time}.log 2>&1
